CREATE DATABASE VITRINA_CARROS
GO
USE VITRINA_CARROS
GO

CREATE TABLE TBL_VEHICULO
(
	ID_VEHICULO SMALLINT PRIMARY KEY IDENTITY(1, 1) NOT NULL, 
	MODELO VARCHAR(30) NOT NULL, 
	ANIO INT,
	PRECIO FLOAT,  
	IMAGEN varbinary(MAX)
)
GO

CREATE TABLE TBL_MARCA
(
	ID_VEHICULO SMALLINT, 
	NOMBRE VARCHAR(30) NOT NULL, 
	PRIMARY KEY(ID_VEHICULO, NOMBRE)
)
GO

ALTER TABLE TBL_MARCA
ADD FOREIGN KEY(ID_VEHICULO) REFERENCES TBL_VEHICULO(ID_VEHICULO)


